env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    js: true
    jsx: true
    ts: true
    tsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - "@jambit/typed-redux-saga"
rules: {}
overrides:
  - files:
      - "./**/*.+(ts|js|tsx|jsx)"
    rules:
      "no-redeclare": 0
      "no-undef": 0
      "no-unused-vars": 0
  - files:
      - "./**/*.+(ts|js|tsx|jsx)"
    excludedFiles:
      - "./**/*.spec.ts"
    rules:
      "@jambit/typed-redux-saga/use-typed-effects": error
      "@jambit/typed-redux-saga/delegate-effects": error
