version: "3.9"
services:
  web:
    image: node:16.16.0-alpine
    ports:
      - "3000:3000"
    volumes:
      - "../../:/app"
    environment:
      NODE_ENV: development
    working_dir: /app
    command: sh -c "cd /app; npm install; npm start"
